version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.7

commands:
  base-command:
    steps:
      - checkout
      - run: make config.env
      - run: sudo pip install -r requirements.txt

jobs:
  flake8:
    executor: machine-executor
    steps:
      - base-command
      - run: make flake8

  test:
    executor: python-executor
    steps:
      - base-command
      - run: make test

workflows:
  version: 2.1
  tests:
    jobs:
      - test
      - flake8