version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.7

commands:
  base-command:
    steps:
      - checkout
      - run: make config.env
      - run: sudo pip install -r requirements-dev.txt

jobs:
  flake8:
    executor: python-executor
    steps:
      - base-command
      - run: make flake8

  test:
    executor: python-executor
    steps:
      - base-command
      - run: make test

  coverage:
    executor: python-executor
    steps:
      - base-command
      - run: make coverage.codacy

workflows:
  version: 2.1
  tests:
    jobs:
      - flake8
      - test
      - coverage
