name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: GitHub Action for Flake8
      uses: cclauss/GitHub-Action-for-Flake8@v0.5.0
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0
