name: Python application coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: make pip.install
      - name: Config .env file
        run: make config.env
      - name: Codacy Coverage
        env:
          CODACY_TOKEN_PROJECT: $
        run: make coverage.codacy
